# Treat most lints as errors
warn-on-all-wildcard-imports = true
cognitive-complexity-threshold = 15
large-error-threshold = 128
vec-box-size-threshold = 4096


# Documentation
doc-valid-idents = [
    "BitTorrent",
    "SHA1",
    "SHA-1",
    "HTTP",
    "HTTPS",
    "TCP",
    "UDP",
]
