[package]
name = "torrust-fuzz"
version = "0.0.0"
edition = "2024"
publish = false


[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"
torrust_lib = { path = "../torrust_lib" }


[[bin]]
name = "bencode"
path = "fuzz_targets/bencode.rs"
test = false
doc = false
bench = false


[[bin]]
name = "metainfo"
path = "fuzz_targets/metainfo.rs"
test = false
doc = false
bench = false
