use super::super::transport::UdpSocket;
use super::super::{AnnounceRequest, TrackerResponse};
use super::{Error, Result};

const PROTOCOL_ID: u64 = 0x41727101980;
const ACTION_CONNECT: u32 = 0;
const ACTION_ANNOUNCE: u32 = 1;

pub fn build_connect_request(tx_id: u32) -> [u8; 16] {
    let mut buf = [0u8; 16];
    buf[0..8].copy_from_slice(&PROTOCOL_ID.to_be_bytes());
    buf[8..12].copy_from_slice(&ACTION_CONNECT.to_be_bytes());
    buf[12..16].copy_from_slice(&tx_id.to_be_bytes());
    buf
}

pub fn parse_connect_response(bytes: &[u8], expected_tx_id: u32) -> Result<u64> {
    if bytes.len() < 16 {
        return Err(Error::InvalidResponse("udp connect response too short".to_owned()));
    }
    let action = u32::from_be_bytes(bytes[0..4].try_into().unwrap());
    let tx_id = u32::from_be_bytes(bytes[4..8].try_into().unwrap());
    if action != ACTION_CONNECT {
        return Err(Error::InvalidResponse(format!("unexpected udp connect action: {action}")));
    }
    if tx_id != expected_tx_id {
        return Err(Error::InvalidResponse("udp connect transaction id mismatch".to_owned()));
    }
    Ok(u64::from_be_bytes(bytes[8..16].try_into().unwrap()))
}

/// `key` should be a random u32 generated by the caller.
pub fn build_announce_request(
    connection_id: u64,
    tx_id: u32,
    key: u32,
    req: &AnnounceRequest,
) -> [u8; 98] {
    let mut buf = [0u8; 98];
    buf[0..8].copy_from_slice(&connection_id.to_be_bytes());
    buf[8..12].copy_from_slice(&ACTION_ANNOUNCE.to_be_bytes());
    buf[12..16].copy_from_slice(&tx_id.to_be_bytes());
    buf[16..36].copy_from_slice(req.info_hash.as_ref());
    buf[36..56].copy_from_slice(req.peer_id.as_ref());
    buf[56..64].copy_from_slice(&req.stats.downloaded.to_be_bytes());
    buf[64..72].copy_from_slice(&req.stats.left.to_be_bytes());
    buf[72..80].copy_from_slice(&req.stats.uploaded.to_be_bytes());
    buf[80..84].copy_from_slice(&req.event.as_udp_code().to_be_bytes());
    buf[84..88].copy_from_slice(&0u32.to_be_bytes());
    buf[88..92].copy_from_slice(&key.to_be_bytes());
    buf[92..96].copy_from_slice(&(-1i32).to_be_bytes());
    buf[96..98].copy_from_slice(&req.port.to_be_bytes());
    buf
}

pub fn parse_announce_response(bytes: &[u8], expected_tx_id: u32) -> Result<TrackerResponse> {
    if bytes.len() < 20 {
        return Err(Error::InvalidResponse("udp announce response too short".to_owned()));
    }
    let action = u32::from_be_bytes(bytes[0..4].try_into().unwrap());
    let tx_id = u32::from_be_bytes(bytes[4..8].try_into().unwrap());
    if action != ACTION_ANNOUNCE {
        return Err(Error::InvalidResponse(format!("unexpected udp announce action: {action}")));
    }
    if tx_id != expected_tx_id {
        return Err(Error::InvalidResponse("udp announce transaction id mismatch".to_owned()));
    }
    let interval = u32::from_be_bytes(bytes[8..12].try_into().unwrap());
    let leechers = u32::from_be_bytes(bytes[12..16].try_into().unwrap());
    let seeders = u32::from_be_bytes(bytes[16..20].try_into().unwrap());
    let peers = super::parse_compact_ipv4_peers(&bytes[20..])?;
    Ok(TrackerResponse {
        interval,
        peers,
        seeders: Some(seeders),
        leechers: Some(leechers),
    })
}

pub async fn announce<S: UdpSocket>(
    socket: &mut S,
    req: &AnnounceRequest,
) -> Result<TrackerResponse> {
    let mut buf = [0u8; 4096];

    let connect_tx = rand::random::<u32>();
    socket.send(&build_connect_request(connect_tx)).await.map_err(Error::Io)?;
    let n = socket.recv(&mut buf).await.map_err(Error::Io)?;
    let connection_id = parse_connect_response(&buf[..n], connect_tx)?;

    let announce_tx = rand::random::<u32>();
    socket
        .send(&build_announce_request(connection_id, announce_tx, rand::random(), req))
        .await
        .map_err(Error::Io)?;
    let n = socket.recv(&mut buf).await.map_err(Error::Io)?;
    parse_announce_response(&buf[..n], announce_tx)
}
